# Generated by Django 3.1.2 on 2020-11-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=200)),
                ('frame', models.PositiveIntegerField(default=0)),
                ('resolution_width', models.PositiveIntegerField(default=0)),
                ('resolution_height', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField(default=0)),
                ('right', models.IntegerField(default=1)),
                ('distance', models.IntegerField(default=100)),
                ('user_width', models.PositiveIntegerField(default=640)),
                ('user_height', models.PositiveIntegerField(default=480)),
            ],
        ),
    ]
