# Generated by Django 3.1.2 on 2020-11-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0002_remove_targetimage_target_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetimage',
            old_name='target_image_byte',
            new_name='target_image',
        ),
    ]
