# Generated by Django 3.1.2 on 2020-11-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0002_auto_20201103_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camera',
            new_name='CameraInfo',
        ),
    ]
