# Generated by Django 3.1.2 on 2020-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0003_cameralist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_left', models.PositiveIntegerField()),
                ('camera_right', models.PositiveIntegerField()),
            ],
        ),
    ]
