# Generated by Django 3.1.2 on 2020-11-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0005_auto_20201116_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CameraInfo',
        ),
    ]
