# Generated by Django 3.1.2 on 2020-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0009_auto_20201117_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetimage',
            name='target_image_real',
        ),
        migrations.AddField(
            model_name='targetimage',
            name='target_bytes',
            field=models.BinaryField(default=b'\x00'),
        ),
        migrations.AlterField(
            model_name='targetimage',
            name='target_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
