# Generated by Django 3.1.2 on 2020-11-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stereovision', '0011_auto_20201117_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetimage',
            name='target_bytes',
        ),
    ]
